DNSAdminEmail = "Jon@9072997.com"
DNSTTL = 300
DNSZone = "withfallback.com."
DNSPassthroughTimeout = "500ms"
RecurseMaxTTL = 86400
RecurseMinTTL = 60
# per eTLD+1
RecurseConcurrencyLimit = 2
RecurseMaxDepth = 7
RecurseServer = "[2600:3c00::3]"
RecurseBufferSize = 1500
MappedPrefix = "2600:3c00:e000:03f5::"
MaxConnectTime = "5s"
MaxIdentifyTime = "1s"
MaxLookupTime = "2s"
ProxyListenAddr = "127.127.127.127:127"
PublicIPv4Addr = "45.33.22.33"
PublicIPv6Addr = "2600:3c00::f03c:92ff:fe4c:684a"
LogAsStringCutoff = 0.80
AbuseIPDBKey = "REDACTED"
AbuseConfidenceThreshold = 10
AbuseRecordTime = "1s"
AbuseRecordLength = 4096
AbuseDBPath = "/var/abuse/db.sqlite3"
AbuseIPExpire = "6h"
AbusePatternExpire = "168h"
AbusePatternsPerIP = 1000
AbuseIPDBVerification = "abuseipdb-verification-Y6KrOhDv"
AbuseSavePatternAfter = 10
AuthUsername = "admin"
AuthPassword = "REDACTED"
